import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ChartColumnBigIcon } from "lucide-react";
import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton } from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import UserDropDown from "./user-dropdown";
import { Toaster } from "sonner";
import UserSingedIn from "@/components/singed-in";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.variable} antialiased`}>
          <nav className="bg-primary p-4 text-white h-20 flex items-center justify-between">
            <Link href="/" className="font-bold text-2xl flex gap-1 items-center">
              <ChartColumnBigIcon className="text-lime-500" /> NextCash
            </Link>
            <div className="flex items-center">
              <SignedOut >
                <div>
                  <Button asChild variant="link" className="text-white">
                    <SignInButton />
                  </Button>

                  <Button asChild variant="link" className="text-white">
                    <SignUpButton/>
                  </Button>
                </div>
              </SignedOut>
              <SignedIn>
                <UserDropDown />
              </SignedIn>
            </div>
          </nav>

          {children}
          <UserSingedIn/>
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider >
  );
}
